# Generated by Django 5.1.2 on 2026-09-12 13:19

import booking.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiongroup',
            name='max_registrations_per_week',
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Limite d'inscriptions hebdomadaires par nageur"),
        ),
        migrations.AlterField(
            model_name='weeklysession',
            name='week',
            field=models.PositiveSmallIntegerField(default=booking.models.GlobalState.get_week, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(53)], verbose_name='semaine'),
        ),
        migrations.AlterField(
            model_name='weeklysession',
            name='year',
            field=models.IntegerField(default=booking.models.GlobalState.get_year, verbose_name='année'),
        ),
    ]
