# Generated by Django 5.1.2 on 2025-09-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="enable_notifications",
            field=models.BooleanField(
                default=True, verbose_name="Activer les notifications"
            ),
        ),
    ]
