# Generated by Django 5.1.2 on 2024-11-21 10:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0002_alter_sessionregistration_swimmer_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sessionregistrationhistory",
            name="unique_swimmer_for_one_session_history",
        ),
        migrations.RemoveField(
            model_name="sessionregistrationhistory",
            name="week",
        ),
        migrations.RemoveField(
            model_name="sessionregistrationhistory",
            name="year",
        ),
        migrations.AddConstraint(
            model_name="sessionregistrationhistory",
            constraint=models.UniqueConstraint(
                models.F("swimmer"),
                models.F("session"),
                name="unique_swimmer_for_one_session_history",
            ),
        ),
    ]
