# Generated by Django 5.1.2 on 2025-09-15 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('booking', '0003_remove_sessionregistrationhistory_unique_swimmer_for_one_session_history_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionregistration',
            options={'verbose_name': 'inscription session', 'verbose_name_plural': 'inscriptions sessions'},
        ),
        migrations.AlterField(
            model_name='sessionregistration',
            name='swimmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nageur'),
        ),
        migrations.CreateModel(
            name='SessionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_registrations_per_week', models.PositiveSmallIntegerField(verbose_name="Limite d'inscriptions hebdomadaires par nageur")),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Groupe')),
            ],
            options={
                'verbose_name': 'groupe de nage',
                'verbose_name_plural': 'groupes de nage',
            },
        ),
        migrations.AlterField(
            model_name='weeklysession',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.sessiongroup', verbose_name='Groupe'),
        ),
        migrations.AlterField(
            model_name='weeklysessionhistory',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.sessiongroup', verbose_name='Groupe'),
        ),
    ]
